[build]
buildCommand = "pip install -r requirements.txt && PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers playwright install chromium && PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers playwright install-deps chromium"

[deploy]
startCommand = "PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers python rr-bot.py"
restartPolicyType = "always"
